const ActionTypes = {
    TOGGLE_SHOP: 'TOGGLE_SHOP',
    CHECKED_ALL_SHOP: 'CHECKED_ALL_SHOP',
    DECREASING_SHOP: 'DECREASING_SHOP',
    INCREASING_SHOP: 'INCREASING_SHOP',
    UN_CHECKED_ALL_SHOP: 'UN_CHECKED_ALL_SHOP',
}

module.exports = ActionTypes